### PR TITLE
Added: ghi open -m <message body>

### PR DESCRIPTION
**Pull request by schwa**
This change adds support for the -m flag on the open command. You can open a new issue via:

ghi open -m 'Lorem ipsum'

### CODE REVIEW

**Comment by jsmits** [comment]
Initially I thought your contribution would allow users to open a new issue without going through the editor. That seemed like a useful addition to me. However, after looking at your code, I can see that creating a new issue with the -m flag still opens the editor. So, my question is: why would you want to do that? It's not that it saves keystrokes. Could you clarify the purpose of the -m flag and why I should add it?

**Comment by schwa** [comment]
With the -m flag used create_edit_issue is passed the issue message in the "text" parameter.

Only if this parameter is None will create_edit_issue call into edit-text - which actually invokes the $EDITOR.

So yes using -m DOES by pass the text editor and will save keystrokes (and more importantly context shifts - a lot of people use GUI based editors and having the editor pop open is sometimes distracting).

It might be a better idea to move the code that handles the -m specified text into open instead of into create_edit_issue.

def create_edit_issue(issue=None, text = None):
    main_text = """# Please explain the issue.

# The first line will be used as the title.

# Lines starting with `#` will be ignored."""

```
if issue:
    issue['main'] = main_text
    template = """%(title)s
```

%(body)s
%(main)s
#

# number:  %(number)s

# user:  %(user)s

# votes:  %(votes)s

# state:  %(state)s

# created:  %(created_at)s""" % issue

```
else:
    template = "\n%s" % main_text
if not text:
    text = edit_text(template)
if not text:
    raise Exception("can not submit an empty issue")
lines = text.splitlines()
title = lines[0]
body = "\n".join(lines[1:]).strip()
return {'title': title, 'body': body}
```

**Comment by schwa** [comment]
(oops. obviously including Python code in the comment was a bad idea)

**Comment by jsmits** [comment]
I pulled it in and added the possibility to add new lines so that it's also possible to create content from the command line, you can do: `ghi o -m 'issue title\nissue content\nsecond content line' . I created a new release (0.3.0) with your changes in it. Thanks.

**Pull request closed without merging**
